<?php

/**
 * PluginwfFeedbackSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginwfFeedbackSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginwfFeedbackSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginwfFeedbackSlot');
    }
}