<?php

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Profiles
 * @property Doctrine_Collection $ProfileCategory
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getName()            Returns the current record's "name" value
 * @method Doctrine_Collection getProfiles()        Returns the current record's "Profiles" collection
 * @method Doctrine_Collection getProfileCategory() Returns the current record's "ProfileCategory" collection
 * @method Category            setId()              Sets the current record's "id" value
 * @method Category            setName()            Sets the current record's "name" value
 * @method Category            setProfiles()        Sets the current record's "Profiles" collection
 * @method Category            setProfileCategory() Sets the current record's "ProfileCategory" collection
 * 
 * @package    eventsfilter
 * @subpackage model
 * @author     Jeremy Kauffman
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategory extends wfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'regexp' => '/^[a-zA-Z0-9][^|~\\`[\\]{}\\/]*$/',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Profile as Profiles', array(
             'refClass' => 'ProfileCategory',
             'local' => 'category_id',
             'foreign' => 'profile_id'));

        $this->hasMany('ProfileCategory', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $mynestedset0 = new Doctrine_Template_MyNestedSet(array(
             'hasManyRoots' => true,
             'rootColumnName' => 'root_id',
             ));
        $this->actAs($timestampable0);
        $this->actAs($mynestedset0);
    }
}