<?php

/**
 * BaseProfileCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $profile_id
 * @property integer $category_id
 * @property Profile $Profile
 * @property Category $Category
 * 
 * @method integer         getProfileId()   Returns the current record's "profile_id" value
 * @method integer         getCategoryId()  Returns the current record's "category_id" value
 * @method Profile         getProfile()     Returns the current record's "Profile" value
 * @method Category        getCategory()    Returns the current record's "Category" value
 * @method ProfileCategory setProfileId()   Sets the current record's "profile_id" value
 * @method ProfileCategory setCategoryId()  Sets the current record's "category_id" value
 * @method ProfileCategory setProfile()     Sets the current record's "Profile" value
 * @method ProfileCategory setCategory()    Sets the current record's "Category" value
 * 
 * @package    eventsfilter
 * @subpackage model
 * @author     Jeremy Kauffman
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfileCategory extends wfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profile_category');
        $this->hasColumn('profile_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profile', array(
             'local' => 'profile_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));
    }
}