<?php

/**
 * BaseSiteDiscipline
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $site_id
 * @property integer $discipline_id
 * @property Site $Site
 * @property Discipline $Discipline
 * 
 * @method integer        getSiteId()        Returns the current record's "site_id" value
 * @method integer        getDisciplineId()  Returns the current record's "discipline_id" value
 * @method Site           getSite()          Returns the current record's "Site" value
 * @method Discipline     getDiscipline()    Returns the current record's "Discipline" value
 * @method SiteDiscipline setSiteId()        Sets the current record's "site_id" value
 * @method SiteDiscipline setDisciplineId()  Sets the current record's "discipline_id" value
 * @method SiteDiscipline setSite()          Sets the current record's "Site" value
 * @method SiteDiscipline setDiscipline()    Sets the current record's "Discipline" value
 * 
 * @package    eventsfilter
 * @subpackage model
 * @author     Jeremy Kauffman
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSiteDiscipline extends wfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('site_discipline');
        $this->hasColumn('site_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('discipline_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Site', array(
             'local' => 'site_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $this->hasOne('Discipline', array(
             'local' => 'discipline_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));
    }
}