<?php

/**
 * BaseEventOwner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $event_id
 * @property integer $user_id
 * @property Event $Event
 * @property sfGuardUser $User
 * 
 * @method integer     getEventId()  Returns the current record's "event_id" value
 * @method integer     getUserId()   Returns the current record's "user_id" value
 * @method Event       getEvent()    Returns the current record's "Event" value
 * @method sfGuardUser getUser()     Returns the current record's "User" value
 * @method EventOwner  setEventId()  Sets the current record's "event_id" value
 * @method EventOwner  setUserId()   Sets the current record's "user_id" value
 * @method EventOwner  setEvent()    Sets the current record's "Event" value
 * @method EventOwner  setUser()     Sets the current record's "User" value
 * 
 * @package    eventsfilter
 * @subpackage model
 * @author     Jeremy Kauffman
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEventOwner extends wfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('event_owner');
        $this->hasColumn('event_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Event', array(
             'local' => 'event_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}