<?php

/**
 * BaseProfileTagging
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Profile $Profile
 * 
 * @method Profile        getProfile() Returns the current record's "Profile" value
 * @method ProfileTagging setProfile() Sets the current record's "Profile" value
 * 
 * @package    eventsfilter
 * @subpackage model
 * @author     Jeremy Kauffman
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfileTagging extends Tagging
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profile', array(
             'local' => 'taggable_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));
    }
}