<?php

/**
 * BaseVenueOwner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $venue_id
 * @property integer $user_id
 * @property Venue $Venue
 * @property sfGuardUser $User
 * 
 * @method integer     getVenueId()  Returns the current record's "venue_id" value
 * @method integer     getUserId()   Returns the current record's "user_id" value
 * @method Venue       getVenue()    Returns the current record's "Venue" value
 * @method sfGuardUser getUser()     Returns the current record's "User" value
 * @method VenueOwner  setVenueId()  Sets the current record's "venue_id" value
 * @method VenueOwner  setUserId()   Sets the current record's "user_id" value
 * @method VenueOwner  setVenue()    Sets the current record's "Venue" value
 * @method VenueOwner  setUser()     Sets the current record's "User" value
 * 
 * @package    eventsfilter
 * @subpackage model
 * @author     Jeremy Kauffman
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVenueOwner extends wfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('venue_owner');
        $this->hasColumn('venue_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Venue', array(
             'local' => 'venue_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}