<?php

/**
 * BaseProfileDiscipline
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $profile_id
 * @property integer $discipline_id
 * @property Profile $Profile
 * @property Discipline $Discipline
 * 
 * @method integer           getProfileId()     Returns the current record's "profile_id" value
 * @method integer           getDisciplineId()  Returns the current record's "discipline_id" value
 * @method Profile           getProfile()       Returns the current record's "Profile" value
 * @method Discipline        getDiscipline()    Returns the current record's "Discipline" value
 * @method ProfileDiscipline setProfileId()     Sets the current record's "profile_id" value
 * @method ProfileDiscipline setDisciplineId()  Sets the current record's "discipline_id" value
 * @method ProfileDiscipline setProfile()       Sets the current record's "Profile" value
 * @method ProfileDiscipline setDiscipline()    Sets the current record's "Discipline" value
 * 
 * @package    eventsfilter
 * @subpackage model
 * @author     Jeremy Kauffman
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfileDiscipline extends wfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profile_discipline');
        $this->hasColumn('profile_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('discipline_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profile', array(
             'local' => 'profile_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $this->hasOne('Discipline', array(
             'local' => 'discipline_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));
    }
}