<?php

/**
 * BaseVenueVenueType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $venue_id
 * @property integer $venue_type_id
 * @property Venue $Venue
 * @property VenueType $VenueType
 * 
 * @method integer        getVenueId()       Returns the current record's "venue_id" value
 * @method integer        getVenueTypeId()   Returns the current record's "venue_type_id" value
 * @method Venue          getVenue()         Returns the current record's "Venue" value
 * @method VenueType      getVenueType()     Returns the current record's "VenueType" value
 * @method VenueVenueType setVenueId()       Sets the current record's "venue_id" value
 * @method VenueVenueType setVenueTypeId()   Sets the current record's "venue_type_id" value
 * @method VenueVenueType setVenue()         Sets the current record's "Venue" value
 * @method VenueVenueType setVenueType()     Sets the current record's "VenueType" value
 * 
 * @package    eventsfilter
 * @subpackage model
 * @author     Jeremy Kauffman
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVenueVenueType extends wfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('venue_venue_type');
        $this->hasColumn('venue_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('venue_type_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Venue', array(
             'local' => 'venue_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $this->hasOne('VenueType', array(
             'local' => 'venue_type_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));
    }
}