<?php

/**
 * BaseProfileUrl
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $profile_id
 * @property string $type
 * @property string $url
 * @property Profile $Profile
 * 
 * @method integer    getProfileId()  Returns the current record's "profile_id" value
 * @method string     getType()       Returns the current record's "type" value
 * @method string     getUrl()        Returns the current record's "url" value
 * @method Profile    getProfile()    Returns the current record's "Profile" value
 * @method ProfileUrl setProfileId()  Sets the current record's "profile_id" value
 * @method ProfileUrl setType()       Sets the current record's "type" value
 * @method ProfileUrl setUrl()        Sets the current record's "url" value
 * @method ProfileUrl setProfile()    Sets the current record's "Profile" value
 * 
 * @package    eventsfilter
 * @subpackage model
 * @author     Jeremy Kauffman
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfileUrl extends wfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profile_url');
        $this->hasColumn('profile_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'url' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profile', array(
             'local' => 'profile_id',
             'foreign' => 'id'));
    }
}