<?php

/**
 * BaseEventTagging
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Event $Event
 * 
 * @method Event        getEvent() Returns the current record's "Event" value
 * @method EventTagging setEvent() Sets the current record's "Event" value
 * 
 * @package    eventsfilter
 * @subpackage model
 * @author     Jeremy Kauffman
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEventTagging extends Tagging
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Event', array(
             'local' => 'taggable_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));
    }
}