<?php

/**
 * EventOwnerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventOwnerTable extends Wf_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventOwnerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventOwner');
    }
}