<?php

/**
 * EventTaggingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventTaggingTable extends TaggingTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventTaggingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventTagging');
    }
}