<?php

/**
 * Event
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    eventsfilter
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Event extends BaseEvent
{
  public function toParams()
  {
    return Event::parameterize($this);
  }
  
  public static function parameterize($event)
  {
    return array('id' => $event['id'], 'name' => myTools::urlify($event['name']));
  }
  
  public function getApiData()
  {
    $data = array(
        'id' => $this->id,
        'name' => $this->name,
        'blurb' => $this->blurb,
        'min_cost' => $this->min_cost,
        'max_cost' => $this->max_cost,
        'url' => $this->url,
        'ticket_url' => $this->ticket_url,
        'is_published' => $this->is_published,
        'venue' => $this->Venue->getApiData(),
        'event_type' => $this->EventType->getApiData(),
        'tags' => $this->getTags()
    );  
    
    foreach(array('profiles' => "Profiles", 'disciplines' => "Disciplines", 'occurences' => "EventOccurances") as $key => $rel)
    {
      foreach($this->$rel as $item) {
        $data[$key][] = $item->getApiData();
      }
      
      if (!isset($data[$key])){
        $data[$key] = null;
      }
    }
    
    if ($this->media_item_id)
    {
      $data += array(
        'original_picture_url' => $this->Picture->getOriginalPath(),
        'scaled_picture_url' => $this->Picture->simpleRender(array('width' => 200, 'maxHeight' => 200, 'height' => false, 'resizeType' => 's'))
      );
    }
    else
    {
      $data += array('original_picture_url' => null, 'scaled_picture_url' => null);
    }
    
        // if ($this->Picture)
    // {
    //   $picture = array(
    //     'width' =>$this->Picture->width,
    //     'height' =>$this->Picture->height,
    //     'slug' => $this->Picture->slug,
    //     'id' => $this->Picture->id,
    //     'title' => $this->Picture->title,
    //     'format' => $this->Picture->format
    //   );

    //   $data['picture'] = $picture;
    // } else {
    //   $data['picture'] = null;
    // }


//    return array('id'=> $this->id);
//    return array_diff_key($data, array('profiles'=> '', 'venue'=> '', 'url'=> ''));
    return $data;
  }
}
