<?php

/**
 * EventProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventProfileTable extends Wf_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventProfile');
    }
}