<?php

/**
 * EventType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    eventsfilter
 * @subpackage model
 * @author     Jeremy Kauffman
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EventType extends BaseEventType
{
  public function toParams()
  {
    return array('id' => $this->id);
  }
  
  public function getApiData()
  {
    return array('id' => $this->id, 'name' => $this->name, 'is_daily' => $this->is_daily);
  }
}
