<?php

/**
 * EventRecurranceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventRecurranceTable extends Wf_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventRecurranceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventRecurrance');
    }
}