<?php

/**
 * LocationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LocationTable extends Wf_Doctrine_Table 
{
  protected static $locationCache = array();
  
  /**
   * Returns an instance of this class.
   *
   * @return object LocationTable
   */
  public static function getInstance() 
  {
    return Doctrine_Core::getTable('Location');
  }
  
  public function findObjectForFilter($id)
  {
    return static::getInstance()->findOneById($id);
  }
  
  public static function findOneByIdCached($id)
  {
    if (!isset(static::$locationCache[$id]))
    {
      static::$locationCache[$id] = static::getInstance()->findOneById($id);
    }
    return static::$locationCache[$id];    
  }
  
  public function buildQueryForProfileIds(Doctrine_Query $query, array $profileIds)
  {
    $rootAlias = $query->getRootAlias();
    $query->innerJoin($rootAlias. '.Profile pf')
      ->andWhereIn('pf.id', $profileIds);
  }
  
  public function buildQueryForEventIds(Doctrine_Query $query, array $eventIds)
  {
    $rootAlias = $query->getRootAlias();
    $query->innerJoin($rootAlias. '.Venue vn')
      ->innerJoin('vn.Event ev')
      ->andWhereIn('ev.id', $eventIds);
  }  

//  public function findAllDisciplineTrees()
//  {
//    $treeObject = $this->getTree();
//    $rootIds = $this->findAllRootIdsByName();
//
//    $trees = array();
//    foreach ($rootIds as $rootId) 
//    {
//      $trees[] = $treeObject->fetchTree(array('root_id' => $rootId));
//    }
//    
//    return $trees;
//  }
}