<?php

/**
 * ProfileGroupMemberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileGroupMemberTable extends Wf_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileGroupMemberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileGroupMember');
    }
}