<?php

/**
 * ProfileDisciplineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileDisciplineTable extends Wf_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileDisciplineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileDiscipline');
    }
}