<?php

/**
 * ProfileOwnerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileOwnerTable extends Wf_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileOwnerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileOwner');
    }
}