<?php

/**
 * ProfileUrlTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileUrlTable extends Wf_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileUrlTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileUrl');
    }
}