<?php

/**
 * ProfileTaggingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileTaggingTable extends TaggingTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileTaggingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileTagging');
    }
}