<?php

/**
 * ProfileCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileCategoryTable extends Wf_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfileCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfileCategory');
    }
}