<?php

/**
 * SiteTagHeadingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SiteTagHeadingTable extends Wf_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SiteTagHeadingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SiteTagHeading');
    }
}