<?php

/**
 * SiteDisciplineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SiteDisciplineTable extends Wf_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SiteDisciplineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SiteDiscipline');
    }
}