<?php

/**
 * TagHeadingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TagHeadingTable extends Wf_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TagHeadingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TagHeading');
    }
   
    public static function collectTagNames($tagHeadings)
    {
      $tagNames = array();
      foreach($tagHeadings as $th)
      {
        foreach($th['Tag'] as $tag)
        {
          $tagNames[] = $tag['name'];
        }
      }      
      return $tagNames;
    }
}