<?php

/**
 * VenueTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VenueTypeTable extends Wf_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VenueTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VenueType');
    }
}