<?php

/**
 * VenueVenueTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VenueVenueTypeTable extends Wf_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VenueVenueTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VenueVenueType');
    }
}