<?php

/**
 * VenueOwnerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VenueOwnerTable extends Wf_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VenueOwnerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VenueOwner');
    }
}