<?php

/**
 * Venue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    eventsfilter
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Venue extends BaseVenue
{
  public function __toString()
  {
    return $this->name;
  }

  public function toParams()
  {
    return Venue::parameterize($this);
  }
  
  public static function parameterize($venue)
  {
    return array('id' => $venue['id'], 'name' => myTools::urlify($venue['name']));
  }
  
  public function hasOwner(sfGuardUser $user)
  {
    foreach($this->VenueOwner as $vo)
    {
      if ($vo->user_id == $user->id)
      {
        return true;
      }
    }
    return false;
  }
  
  public function getApiData()
  {
    $data = array(
        'id' => $this->id, 
        'name' => $this->name,
        'blurb' => $this->blurb,
        'location' => $this->Location->getApiData(),
        'url' => $this->url
    );
    foreach($this->getAddressFields() as $field)
    {
      $data[$field] = $this->$field;
    }
    return $data;
  }
           
}
