generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Site
    theme:                 aAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          site_admin
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=name, org_abbr, org_name, theme, _domain, _logo, created_at]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
