<?php

/**
 * sfGuardUserPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserPermissionTable extends PluginsfGuardUserPermissionTable
{
  /**
   * Returns an instance of this class.
   *
   * @return object sfGuardUserPermissionTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('sfGuardUserPermission');
  }
  
  public static function findPermissionNamesForUser(sfGuardUser $user, Site $site)
  {
    $groups = sfGuardGroupTable::findGroupsForUserAndSite($user, $site);
    
    $permissions = array();
    foreach($groups as $group)
    {
      foreach($group->getPermissions() as $permission)
      {
        $permissions[$permission->id] = $permission->name;
      }
    }
    
    return $permissions;
  }
}