generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Tag
    theme:                 aAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tag_admin
    with_doctrine_route:   1
    
    
    config:      
      list:
        sort: [name, asc]
        title: Tags Admin
        display: [ =name, TagHeading, _profile_count, _event_count]
        object_actions: []
        actions:
          new:
            label: <span class="icon"></span> New Tag
            action: new
            params:
              class: a-btn big icon a-add
      
      form:
        class: AdminTagForm
      
      filter: 
        class: false
              
      edit:
        title: Edit Tag
        
      new:
        title: New Tag