<?php

/**
 * BaseaSmartSlideshowSlot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    eventsfilter
 * @subpackage model
 * @author     Jeremy Kauffman
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseaSmartSlideshowSlot extends aSlot
{
    public function setUp()
    {
        parent::setUp();
        
    }
}