<?php

/**
 * aAccessTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aAccessTable extends PluginaAccessTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aAccessTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aAccess');
    }
}