<?php

/**
 * aAreaVersionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aAreaVersionTable extends PluginaAreaVersionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aAreaVersionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aAreaVersion');
    }
}