<?php

/**
 * aAreaVersionSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aAreaVersionSlotTable extends PluginaAreaVersionSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aAreaVersionSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aAreaVersionSlot');
    }
}