<?php

/**
 * aFeedSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aFeedSlotTable extends PluginaFeedSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aFeedSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aFeedSlot');
    }
}