<?php

/**
 * aGroupAccessTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aGroupAccessTable extends PluginaGroupAccessTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aGroupAccessTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aGroupAccess');
    }
}