<?php

/**
 * aImageSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aImageSlotTable extends PluginaImageSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aImageSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aImageSlot');
    }
}