<?php

/**
 * aLuceneUpdateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aLuceneUpdateTable extends PluginaLuceneUpdateTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aLuceneUpdateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aLuceneUpdate');
    }
}