<?php

/**
 * aMediaItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aMediaItemTable extends PluginaMediaItemTable 
{

  /**
   * Returns an instance of this class.
   *
   * @return object aMediaItemTable
   */
  public static function getInstance() 
  {
    return Doctrine_Core::getTable('aMediaItem');
  }
  
  static public function getBrowseQuery($params)
  {
    $query = parent::getBrowseQuery($params);
    if (sfContext::hasInstance())
    {
      $user = sfContext::getInstance()->getUser();
      if ($user->getGuardUser() && !$user->hasCredential(aMediaTools::getOption('admin_credential')))
      {
        $query->addWhere('aMediaItem.owner_id = ?', $user->getGuardUser()->getId());
      }
    }
    return $query;
  }
}