<?php

/**
 * aMediaBrowserSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aMediaBrowserSlotTable extends PluginaMediaBrowserSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aMediaBrowserSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aMediaBrowserSlot');
    }
}