<?php

/**
 * aMediaItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    eventsfilter
 * @subpackage model
 * @author     Jeremy Kauffman
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class aMediaItem extends PluginaMediaItem
{
    /**
   * DOCUMENT ME
   * @param mixed $format
   * @return mixed
   */
  public function getRelativeOriginalPath($format = false)
  {
    return str_replace(sfConfig::get('sf_web_dir'), '', $this->getOriginalPath($format));
  }
 
    /**
   * Used to be in my_aHelper prior to deletion, didn't want to mess with this.
   */
  public function simpleRender($options = array(), $absolute = false)
  {
    $dimensions = aDimensions::constrain($this->width, $this->height, $this->format, $options);
    return $this->getEmbedCode($dimensions['width'], $dimensions['height'], $dimensions['resizeType'], $dimensions['format'], $absolute, $options);
  }
}
