<?php

/**
 * aNewRichTextSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aNewRichTextSlotTable extends PluginaNewRichTextSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aNewRichTextSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aNewRichTextSlot');
    }
}