<?php

/**
 * aPDFSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aPDFSlotTable extends PluginaPDFSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aPDFSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aPDFSlot');
    }
}