<?php

/**
 * aRawHTMLSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aRawHTMLSlotTable extends PluginaRawHTMLSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aRawHTMLSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aRawHTMLSlot');
    }
}