<?php

/**
 * aRedirectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aRedirectTable extends PluginaRedirectTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aRedirectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aRedirect');
    }
}