<?php

/**
 * aRichTextSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aRichTextSlotTable extends PluginaRichTextSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aRichTextSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aRichTextSlot');
    }
}