<?php

/**
 * aSlideshowSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aSlideshowSlotTable extends PluginaSlideshowSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aSlideshowSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aSlideshowSlot');
    }
}