<?php

/**
 * aSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aSlotTable extends PluginaSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aSlot');
    }
}