<?php

/**
 * aSlotMediaItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aSlotMediaItemTable extends PluginaSlotMediaItemTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aSlotMediaItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aSlotMediaItem');
    }
}