<?php

/**
 * aTextSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aTextSlotTable extends PluginaTextSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aTextSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aTextSlot');
    }
}