<?php

/**
 * aBlogItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aBlogItemTable extends PluginaBlogItemTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aBlogItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aBlogItem');
    }
}