<?php

/**
 * aBlogEditorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aBlogEditorTable extends PluginaBlogEditorTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aBlogEditorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aBlogEditor');
    }
}