<?php

/**
 * aBlogSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aBlogSlotTable extends PluginaBlogSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aBlogSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aBlogSlot');
    }
}