<?php

/**
 * aEventSingleSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aEventSingleSlotTable extends PluginaEventSingleSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aEventSingleSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aEventSingleSlot');
    }
}