<?php

/**
 * aEventSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aEventSlotTable extends PluginaEventSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aEventSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aEventSlot');
    }
}