<?php

/**
 * aEventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aEventTable extends PluginaEventTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aEventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aEvent');
    }
}