<?php

/**
 * wfFeedbackSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class wfFeedbackSlotTable extends PluginwfFeedbackSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object wfFeedbackSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('wfFeedbackSlot');
    }
}